CC=g++
FLAGS=-std=c++11

MAIN=main.cpp
EXECUTABLE=akinator

SOURCES=Akinator.cpp
HEADERS=Akinator.h Node.h

all: build

build:  $(SOURSES) $(HEADERS) 
	$(CC) $(FLAGS) $(MAIN) $(SOURCES) -o $(EXECUTABLE)



